In [1]:
import torch

In [2]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
c = torch.tensor([3, 4])


In [3]:
torch.stack((a, b, c), dim=1)

tensor([[1, 3, 3],
        [2, 4, 4]])

In [5]:
a = torch.tensor([[1], [2]])
b = torch.tensor([[1], [2]])

torch.cat([a, b], dim=1)

tensor([[1, 1],
        [2, 2]])

In [1]:
alpha = [1.0] * 5  # Example class weights


In [2]:
alpha

[1.0, 1.0, 1.0, 1.0, 1.0]

In [3]:
import torch
a = [1, 2, torch.tensor(3)]
torch.tensor(a)

tensor([1, 2, 3])

In [1]:
import cv2

if not cv2.cuda.getCudaEnabledDeviceCount():
    print("CUDA-enabled GPU not found. Exiting...")

CUDA-enabled GPU not found. Exiting...


In [2]:
from sklearn.metrics import precision_recall_fscore_support
import numpy as np


In [6]:
y_pred = np.array([1, 1, 2, 0, 3, 4, 2])
targets = np.array([1, 0, 2, 1, 4, 4, 3])

precision_recall_fscore_support(targets, y_pred, average='macro')


(0.4, 0.4, 0.3666666666666666, None)

In [8]:
y_pred = np.array([1, 0, 2, 1, 4, 4, 2])
targets = np.array([1, 0, 2, 1, 4, 4, 3])

precision_recall_fscore_support(targets, y_pred, average='macro')

c:\Users\User\.conda\envs\EnvMasoudi\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


(0.7, 0.8, 0.7333333333333333, None)

In [9]:
import torch

In [15]:
a = torch.Tensor([1, 2, 3])
b = torch.tensor([1, 2, 3.])

In [16]:
a

tensor([1., 2., 3.])

In [17]:
b

tensor([1., 2., 3.])

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class FocalLoss(nn.Module):
    def __init__(self, alpha=None, gamma=2, label_smoothing=0):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.label_smoothing = label_smoothing

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none', label_smoothing=self.label_smoothing)
        pt = torch.exp(-ce_loss)
        loss = (self.alpha[targets] * (1 - pt) ** self.gamma * ce_loss).mean()
        return loss

In [34]:
inputs = torch.tensor([[-2, -5, 3, 6, 12.], [-2, -5, 3, 6, 12.]])
targets = torch.tensor([4, 4])

ce_loss = F.cross_entropy(inputs, targets, reduction='none', label_smoothing=0.1)
ce_loss

tensor([0.9226, 0.9226])

In [9]:
pt = torch.exp(-ce_loss)
pt

tensor([0.9974, 0.9974])

In [10]:
gamma = 1
alpha = torch.tensor([0.2, 5, 3, 2, 3])
alpha[targets]

tensor([3., 3.])

In [11]:
loss = (alpha[targets] * (1 - pt) ** gamma * ce_loss).mean()
loss


tensor(2.0249e-05)

In [33]:
loss_fn = FocalLoss(alpha=alpha, gamma=1, label_smoothing=0.0)
loss_fn(inputs, targets)

tensor(2.0249e-05)

In [3]:
alpha = torch.tensor([0.5]) * 5
alpha

tensor([2.5000])